---
swagger: '2.0'
host: "127.0.0.1:5000"
info:
  description: |
    API managing data integration.

    Enables coverages, contributors declaration and management.
    Also offers the possibility to POST data to update.

    You can help on [Tartare's github page](https://github.com/CanalTP/tartare).

  version: 0.1.0
  title: Tartare API
  contact:
    name: www.navitia.io
  license:
    name: AGPLv3
    url: http://www.gnu.org/licenses/
schemes:
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
  - multipart/form-data
# format of the responses to the client (Accepts)
produces:
  - application/json

tags:
  -
    name: "coverages"
    description: "Manage coverages"
  -
    name: "contributors"
    description: "Manage contributors"
  -
    name: "data"
    description: "Manage data api"

paths:
  /:
    get:
      summary: Display available endpoints
      produces:
        - application/json
      responses:
        200:
          description: Array of links


  /coverages:

    get:
      summary: Display available coverages
      tags:
        - coverages
      responses:
        200:
          description: Array of coverages
          schema:
            title: coverages
            type: array
            items:
              $ref: '#/definitions/coverage'

    post:
      summary: Create a new coverage
      tags:
        - coverages
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Coverage object that needs to be added to Tartare
          required: true
          schema:
            $ref: "#/definitions/coverage"
      responses:
        200:
          description: Created coverage
          schema:
            $ref: "#/definitions/coverage"

  /coverages/{coverage_id}:
    patch:
      summary: Modify a coverage configuration
      tags:
        - coverages
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: coverage_id
          type: string
          description: Identifier of the coverage that needs to be modified
          required: true
        - in: body
          name: body
          description: Attributes of the coverage <coverage_id> that needs to be modified
          required: true
          schema:
            $ref: "#/definitions/coverage"
      responses:
        200:
          description: Modified coverage
          schema:
            $ref: "#/definitions/coverage"
        400:
          description: Error in provided data
          schema:
            $ref: "#/definitions/error"
    delete:
      summary: Delete a coverage
      tags:
        - coverages
      produces:
        - application/json
      parameters:
        - in: path
          name: coverage_id
          type: string
          description: Identifier of the coverage that needs to be modified
          required: true
      responses:
        204:
          description: Coverage <coverage_id> correctly deleted
        404:
          description: coverage_id not found
          schema:
            $ref: "#/definitions/message"

  /coverages/{coverage_id}/grid_calendar:
    post:
      summary: Handle a grid_calendar file to coverage <coverage_id> for processing
      tags:
        - coverages
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - in: path
          name: coverage_id
          type: string
          description: Identifier of the coverage that needs to be modified
          required: true
        - in: formData
          name: file
          type: file
          description: File to be sent to the coverage. Data type is automatically detected
          required: true
      responses:
        200:
          description: OK
        400:
          description: Error
          schema:
            $ref: '#/definitions/message'

  /coverages/{coverage_id}/data/{data_type}:
    get:
      summary: Retrieve the latest data file of the specified coverage
      tags:
        - coverages
        - data
      produces:
        - application/json
        - application/zip
      parameters:
        - in: path
          name: coverage_id
          type: string
          description: Identifier of the manipulated coverage
          required: true
        - in: path
          name: data_type
          type: string
          enum: ["ntfs"]
          description: Type of data beeing manipulated
          required: true
      responses:
        200:
          description: Return the data file requested
        400:
          description: Error
          schema:
            $ref: '#/definitions/message'
        404:
          description: Error
          schema:
            $ref: '#/definitions/message'
    post:
      summary: Send a new data file to coverage <coverage_id> for processing
      tags:
        - coverages
        - data
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - in: path
          name: coverage_id
          type: string
          description: Identifier of the manipulated coverage
          required: true
        - in: path
          name: data_type
          type: string
          enum: ["ntfs"]
          description: Type of data beeing manipulated
          required: true
        - in: formData
          name: file
          type: file
          description: File to be sent to the coverage. Data type is automatically detected
          required: true
      responses:
        200:
          description: Return the data file requested
        400:
          description: Error
          schema:
            $ref: '#/definitions/message'
        404:
          description: Error
          schema:
            $ref: '#/definitions/message'

  /coverages/{coverage_id}/environments/{environment_type}/data_update:
    post:
      summary: Handle a file to coverage <coverage_id> for processing (NTFS, GTFS, OSM, Fare, POI, synonym). (DEPRECATED)
      tags:
        - coverages
        - data
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - in: path
          name: coverage_id
          type: string
          description: Identifier of the coverage that needs to be modified
          required: true
        - in: path
          name: environment_type
          type: string
          enum: ["integration", "preproduction", "production"]
          description: Environment of the coverage <coverage_id> the DATA will be sent to
          required: true
        - in: formData
          name: file
          type: file
          description: File to be sent to the coverage. Data type is automatically detected
          required: true
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/message'
        400:
          description: Error
          schema:
            $ref: '#/definitions/message'
        404:
          description: Error
          schema:
            $ref: '#/definitions/message'


  /contributors:
    get:
      summary: Display available contributors
      tags:
        - contributors
      produces:
        - application/json
      responses:
        200:
          description: Array of contributors
          schema:
            title: contributors
            type: array
            items:
              $ref: '#/definitions/contributor_type'
    post:
      summary: Create a new contributor
      tags:
        - contributors
      produces:
        - application/json
      consumes:
        - application/json
      responses:
        201:
          description: Contributor created
          schema:
            $ref: '#/definitions/contributor_obj'
        400:
          description: Error
          schema :
            $ref: '#/definitions/error'

  /contributors/{contributor_id}:
    get:
      summary: Display contributor info
      tags:
        - contributors
      produces:
        - application/json
      parameters:
        - in: path
          name: contributor_id
          type: string
          description: Identifier of the contributor
          required: true
      responses:
        200:
          description: Requested contributor
          schema:
            $ref: '#/definitions/contributor_obj'
    delete:
      summary: delete contributor
      tags:
        - contributors
      produces:
        - application/json
      parameters:
        - in: path
          name: contributor_id
          type: string
          description: Identifier of the contributor
          required: true
      responses:
        204:
          description: Delete OK
          schema:
            $ref: '#/definitions/contributor_obj'
    patch:
      summary: Modify contributor info
      tags:
        - contributors
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: path
          name: contributor_id
          type: string
          description: Identifier of the contributor
          required: true
        - in: body
          name: body
          description: Attributes of the contributor <contributor_id> that needs to be modified.
          required: true
          schema:
            $ref: "#/definitions/contributor_type"
      responses:
        200:
          description: Requested contributor
          schema:
            $ref: '#/definitions/contributor_obj'
        400:
          description: Error
          schema :
            $ref: '#/definitions/error'


definitions:

  coverage:
    type: object
    properties:
      id:
        type: string
        example: fr-auv
      name:
        type: string
        example: auv
      grid_calendar_id:
        type: string
        example: 5810cb2d3c96b7000108d074
      environments:
        $ref: "#/definitions/environments"

  environments:
    type: object
    properties:
      production:
        $ref: "#/definitions/environment_type"
      preproduction:
        $ref: "#/definitions/environment_type"
      integration:
        $ref: "#/definitions/environment_type"

  environment_type:
    type: object
    properties:
      name:
        type: string
        example: integration
      tyr_url:
        type: string
        example: http://tyr.dev.canaltp.fr/v0/jobs/fr-auv
      current_ntfs_id:
        type: string
        example: 5810cb2d3c96b7000108d074

  contributor_obj:
    type: object
    properties:
      contributor:
        $ref: "#/definitions/contributor_type"

  contributor_type:
    type: object
    properties:
      id:
        type: string
        example: contrib-tan
      name:
        type: string
        example: TAN
      data_prefix:
        type: string
        example: AAA

  message:
    type: object
    properties:
      message:
        type: string
        example: impossible to add coverage <coverage_id>

  error:
    type: object
    properties:
      error:
        type: string
        example: The modification of the id is not possible
